version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "until nc -z db 5432; do sleep 1; done;
      uvicorn main:app --host 0.0.0.0 --port 443
      --ssl-certfile=/usr/src/app/cert.pem --ssl-keyfile=/usr/src/app/key.pem"
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"    # Maps HTTP traffic
      - "443:443"  # Maps HTTPS traffic
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123@db:5432/postgres

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres

volumes:
  postgres_data:
